[package]
name = "bevy-steamworks"
version = "0.6.0"
authors = ["james7132 <contact@jamessliu.com>"]
edition = "2021"
description = "A Bevy plugin for integrating with the Steamworks SDK."
repository = "https://github.com/james7132/bevy-steamworks"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "gamedev", "steam"]

[features]
default = []

[dependencies]
bevy_log = "0.10"
bevy_app = "0.10"
bevy_ecs = "0.10"
steamworks = "0.9"
parking_lot = "0.12"

[dev-dependencies]
bevy = "0.10"
