[package]
name = "bevy-steamworks"
version = "0.2.0"
authors = ["james7132 <contact@jamessliu.com>"]
edition = "2018"
description = "A Bevy plugin for integrating with the Steamworks SDK."
repository = "https://github.com/james7132/bevy-steamworks"
license = "MIT or Apache-2.0"
keywords = ["bevy", "gamedev", "steam"]

[package.metadata.docs.rs]
features = [ "docs-only" ]

[features]
default = []
# Skip looking for the steamworks sdk for docs builds
docs-only = ["steamworks/docs-only"]

[dependencies]
bevy_log = "0.6"
bevy_app = "0.6"
bevy_ecs = "0.6"
steamworks = "0.8"